# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera.proto',
  package='camera',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63\x61mera.proto\x12\x06\x63\x61mera\"\x1f\n\nUrlRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\"\x1f\n\x0bUrlResponse\x12\x10\n\x08response\x18\x01 \x01(\t2F\n\x0eImageDetection\x12\x34\n\x07SendUrl\x12\x12.camera.UrlRequest\x1a\x13.camera.UrlResponse\"\x00\x62\x06proto3')
)




_URLREQUEST = _descriptor.Descriptor(
  name='UrlRequest',
  full_name='camera.UrlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_url', full_name='camera.UrlRequest.image_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=55,
)


_URLRESPONSE = _descriptor.Descriptor(
  name='UrlResponse',
  full_name='camera.UrlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='camera.UrlResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['UrlRequest'] = _URLREQUEST
DESCRIPTOR.message_types_by_name['UrlResponse'] = _URLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UrlRequest = _reflection.GeneratedProtocolMessageType('UrlRequest', (_message.Message,), dict(
  DESCRIPTOR = _URLREQUEST,
  __module__ = 'camera_pb2'
  # @@protoc_insertion_point(class_scope:camera.UrlRequest)
  ))
_sym_db.RegisterMessage(UrlRequest)

UrlResponse = _reflection.GeneratedProtocolMessageType('UrlResponse', (_message.Message,), dict(
  DESCRIPTOR = _URLRESPONSE,
  __module__ = 'camera_pb2'
  # @@protoc_insertion_point(class_scope:camera.UrlResponse)
  ))
_sym_db.RegisterMessage(UrlResponse)



_IMAGEDETECTION = _descriptor.ServiceDescriptor(
  name='ImageDetection',
  full_name='camera.ImageDetection',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=90,
  serialized_end=160,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendUrl',
    full_name='camera.ImageDetection.SendUrl',
    index=0,
    containing_service=None,
    input_type=_URLREQUEST,
    output_type=_URLRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEDETECTION)

DESCRIPTOR.services_by_name['ImageDetection'] = _IMAGEDETECTION

# @@protoc_insertion_point(module_scope)
