# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import camera_pb2 as camera__pb2


class ImageDetectionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendUrl = channel.unary_unary(
        '/camera.ImageDetection/SendUrl',
        request_serializer=camera__pb2.UrlRequest.SerializeToString,
        response_deserializer=camera__pb2.UrlResponse.FromString,
        )


class ImageDetectionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendUrl(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageDetectionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendUrl': grpc.unary_unary_rpc_method_handler(
          servicer.SendUrl,
          request_deserializer=camera__pb2.UrlRequest.FromString,
          response_serializer=camera__pb2.UrlResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'camera.ImageDetection', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
