# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inms.proto',
  package='inms',
  syntax='proto3',
  serialized_pb=_b('\n\ninms.proto\x12\x04inms\"G\n\x1a\x44\x65tectedIngredientsRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x13\n\x0bingredients\x18\x02 \x03(\t\";\n\x1b\x44\x65tectedIngredientsResponse\x12\x1c\n\x06status\x18\x01 \x01(\x0b\x32\x0c.inms.Status\"-\n\x15GetIngredientsRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\"K\n\x16GetIngredientsResponse\x12\x13\n\x0bingredients\x18\x01 \x03(\t\x12\x1c\n\x06status\x18\x02 \x01(\x0b\x32\x0c.inms.Status\"\\\n\x11GetRecipesRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x13\n\x0bingredients\x18\x02 \x03(\t\x12\x1c\n\x14\x61llergic_ingredients\x18\x03 \x03(\t\"R\n\x12GetRecipesResponse\x12\x1e\n\x07recipes\x18\x01 \x03(\x0b\x32\r.inms.Recipes\x12\x1c\n\x06status\x18\x02 \x01(\x0b\x32\x0c.inms.Status\"w\n\x07Recipes\x12\x13\n\x0brecipe_name\x18\x01 \x01(\t\x12\x13\n\x0bingredients\x18\x02 \x03(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x18\n\x10preparation_time\x18\x04 \x01(\t\x12\x15\n\rcalorie_count\x18\x05 \x01(\x01\"D\n\x06Status\x12%\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x10.inms.StatusCode\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t*B\n\nStatusCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\r\n\tNOT_FOUND\x10\x02\x12\x0b\n\x07\x46\x41ILURE\x10\x03\x32o\n\tDetection\x12\x62\n\x19UpdateDetectedIngredients\x12 .inms.DetectedIngredientsRequest\x1a!.inms.DetectedIngredientsResponse\"\x00\x32\xa3\x01\n\x0f\x42\x61\x63kendRequests\x12M\n\x0eGetIngredients\x12\x1b.inms.GetIngredientsRequest\x1a\x1c.inms.GetIngredientsResponse\"\x00\x12\x41\n\nGetRecipes\x12\x17.inms.GetRecipesRequest\x1a\x18.inms.GetRecipesResponse\"\x00\x62\x06proto3')
)

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='inms.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_FOUND', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=647,
  serialized_end=713,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
UNKNOWN = 0
SUCCESS = 1
NOT_FOUND = 2
FAILURE = 3



_DETECTEDINGREDIENTSREQUEST = _descriptor.Descriptor(
  name='DetectedIngredientsRequest',
  full_name='inms.DetectedIngredientsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_id', full_name='inms.DetectedIngredientsRequest.container_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ingredients', full_name='inms.DetectedIngredientsRequest.ingredients', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=91,
)


_DETECTEDINGREDIENTSRESPONSE = _descriptor.Descriptor(
  name='DetectedIngredientsResponse',
  full_name='inms.DetectedIngredientsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='inms.DetectedIngredientsResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=152,
)


_GETINGREDIENTSREQUEST = _descriptor.Descriptor(
  name='GetIngredientsRequest',
  full_name='inms.GetIngredientsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_id', full_name='inms.GetIngredientsRequest.container_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=199,
)


_GETINGREDIENTSRESPONSE = _descriptor.Descriptor(
  name='GetIngredientsResponse',
  full_name='inms.GetIngredientsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ingredients', full_name='inms.GetIngredientsResponse.ingredients', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='inms.GetIngredientsResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=276,
)


_GETRECIPESREQUEST = _descriptor.Descriptor(
  name='GetRecipesRequest',
  full_name='inms.GetRecipesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_id', full_name='inms.GetRecipesRequest.container_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ingredients', full_name='inms.GetRecipesRequest.ingredients', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allergic_ingredients', full_name='inms.GetRecipesRequest.allergic_ingredients', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=370,
)


_GETRECIPESRESPONSE = _descriptor.Descriptor(
  name='GetRecipesResponse',
  full_name='inms.GetRecipesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recipes', full_name='inms.GetRecipesResponse.recipes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='inms.GetRecipesResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=454,
)


_RECIPES = _descriptor.Descriptor(
  name='Recipes',
  full_name='inms.Recipes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recipe_name', full_name='inms.Recipes.recipe_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ingredients', full_name='inms.Recipes.ingredients', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_url', full_name='inms.Recipes.image_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preparation_time', full_name='inms.Recipes.preparation_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calorie_count', full_name='inms.Recipes.calorie_count', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=575,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='inms.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='inms.Status.status_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='inms.Status.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=645,
)

_DETECTEDINGREDIENTSRESPONSE.fields_by_name['status'].message_type = _STATUS
_GETINGREDIENTSRESPONSE.fields_by_name['status'].message_type = _STATUS
_GETRECIPESRESPONSE.fields_by_name['recipes'].message_type = _RECIPES
_GETRECIPESRESPONSE.fields_by_name['status'].message_type = _STATUS
_STATUS.fields_by_name['status_code'].enum_type = _STATUSCODE
DESCRIPTOR.message_types_by_name['DetectedIngredientsRequest'] = _DETECTEDINGREDIENTSREQUEST
DESCRIPTOR.message_types_by_name['DetectedIngredientsResponse'] = _DETECTEDINGREDIENTSRESPONSE
DESCRIPTOR.message_types_by_name['GetIngredientsRequest'] = _GETINGREDIENTSREQUEST
DESCRIPTOR.message_types_by_name['GetIngredientsResponse'] = _GETINGREDIENTSRESPONSE
DESCRIPTOR.message_types_by_name['GetRecipesRequest'] = _GETRECIPESREQUEST
DESCRIPTOR.message_types_by_name['GetRecipesResponse'] = _GETRECIPESRESPONSE
DESCRIPTOR.message_types_by_name['Recipes'] = _RECIPES
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectedIngredientsRequest = _reflection.GeneratedProtocolMessageType('DetectedIngredientsRequest', (_message.Message,), dict(
  DESCRIPTOR = _DETECTEDINGREDIENTSREQUEST,
  __module__ = 'inms_pb2'
  # @@protoc_insertion_point(class_scope:inms.DetectedIngredientsRequest)
  ))
_sym_db.RegisterMessage(DetectedIngredientsRequest)

DetectedIngredientsResponse = _reflection.GeneratedProtocolMessageType('DetectedIngredientsResponse', (_message.Message,), dict(
  DESCRIPTOR = _DETECTEDINGREDIENTSRESPONSE,
  __module__ = 'inms_pb2'
  # @@protoc_insertion_point(class_scope:inms.DetectedIngredientsResponse)
  ))
_sym_db.RegisterMessage(DetectedIngredientsResponse)

GetIngredientsRequest = _reflection.GeneratedProtocolMessageType('GetIngredientsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETINGREDIENTSREQUEST,
  __module__ = 'inms_pb2'
  # @@protoc_insertion_point(class_scope:inms.GetIngredientsRequest)
  ))
_sym_db.RegisterMessage(GetIngredientsRequest)

GetIngredientsResponse = _reflection.GeneratedProtocolMessageType('GetIngredientsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETINGREDIENTSRESPONSE,
  __module__ = 'inms_pb2'
  # @@protoc_insertion_point(class_scope:inms.GetIngredientsResponse)
  ))
_sym_db.RegisterMessage(GetIngredientsResponse)

GetRecipesRequest = _reflection.GeneratedProtocolMessageType('GetRecipesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRECIPESREQUEST,
  __module__ = 'inms_pb2'
  # @@protoc_insertion_point(class_scope:inms.GetRecipesRequest)
  ))
_sym_db.RegisterMessage(GetRecipesRequest)

GetRecipesResponse = _reflection.GeneratedProtocolMessageType('GetRecipesResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRECIPESRESPONSE,
  __module__ = 'inms_pb2'
  # @@protoc_insertion_point(class_scope:inms.GetRecipesResponse)
  ))
_sym_db.RegisterMessage(GetRecipesResponse)

Recipes = _reflection.GeneratedProtocolMessageType('Recipes', (_message.Message,), dict(
  DESCRIPTOR = _RECIPES,
  __module__ = 'inms_pb2'
  # @@protoc_insertion_point(class_scope:inms.Recipes)
  ))
_sym_db.RegisterMessage(Recipes)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'inms_pb2'
  # @@protoc_insertion_point(class_scope:inms.Status)
  ))
_sym_db.RegisterMessage(Status)



_DETECTION = _descriptor.ServiceDescriptor(
  name='Detection',
  full_name='inms.Detection',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=715,
  serialized_end=826,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateDetectedIngredients',
    full_name='inms.Detection.UpdateDetectedIngredients',
    index=0,
    containing_service=None,
    input_type=_DETECTEDINGREDIENTSREQUEST,
    output_type=_DETECTEDINGREDIENTSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTION)

DESCRIPTOR.services_by_name['Detection'] = _DETECTION


_BACKENDREQUESTS = _descriptor.ServiceDescriptor(
  name='BackendRequests',
  full_name='inms.BackendRequests',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=829,
  serialized_end=992,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetIngredients',
    full_name='inms.BackendRequests.GetIngredients',
    index=0,
    containing_service=None,
    input_type=_GETINGREDIENTSREQUEST,
    output_type=_GETINGREDIENTSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRecipes',
    full_name='inms.BackendRequests.GetRecipes',
    index=1,
    containing_service=None,
    input_type=_GETRECIPESREQUEST,
    output_type=_GETRECIPESRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKENDREQUESTS)

DESCRIPTOR.services_by_name['BackendRequests'] = _BACKENDREQUESTS

# @@protoc_insertion_point(module_scope)
